services:
  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudformation,dynamodb,iam,s3,ssm,sts
      - DEBUG=0
      - PERSISTENCE=1

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DYNAMO_ENDPOINT=http://localstack:4566
